export const TOGGLE_VEHICLE = 'TOGGLE_VEHICLE';

export const FETCH_VEHICLES = {
  REQUEST: 'FETCH_VEHICLES_REQUEST',
  FAILURE: 'FETCH_VEHICLES_FAILURE',
  SUCCESS: 'FETCH_VEHICLES_SUCCESS'
};

export const VISIBILITY_FILTERS = {
  CHANGE_COLOR: 'CHANGE_COLOR',
  CHANGE_BRAND: 'CHANGE_BRAND',
  CHANGE_TYPE: 'CHANGE_TYPE'
};
